### ISSUE TITLE
应用到有没有全局的设置规则？

### ISSUE THREAD

**Issue by Z-fly** [francis-zhao/userstyles#1]
![image](https://user-images.githubusercontent.com/10470892/104741039-a2e23c80-5783-11eb-881a-83cced93ed4f.png)

**Comment by Z-fly** [comment]
好像是全局的？

**Comment by Z-fly** [comment]
如果要手动指定部分网站是怎么写规则？

**Comment by bamf2077** [comment]
> 好像是全局的？

是全局通用的，Greasy Fork 上看到的“应用到”的那几个网站有部分文本自行设置了字体，我这里又单独写了规则强制替换，因为全局强制替换有一些不良后果。

**Comment by bamf2077** [comment]
> 如果要手动指定部分网站是怎么写规则？

如果是因为部分网页字体无法适配，可以直接反馈给我，我直接添加规则提交更新，Stylus / Tampermonkey 会在3天左右自动更新。

如果你是想自己添加自定义样式，可以参考这两个网址：

https://github.com/openstyles/stylus/wiki/Writing-UserCSS

https://developer.mozilla.org/zh-CN/docs/Web/CSS/@document

对某个网址生效：
```css
@-moz-document url("https://example.com/") {
  /* 你的代码 */
}
```

对以某字段开头的网址生效：
```css
@-moz-document url-prefix("https://example.com/abc/") {
  /* 你的代码 */
}
```

对某个域名和子域名的所有网址生效：
```css
@-moz-document domain("example.com") {
  /* 你的代码 */
}
```

使用正则表达式匹配网址：
```css
@-moz-document regexp() {
  /* 你的代码 */
}
```

**Comment by Z-fly** [comment]
@francis-zhao http://bbs.pcbeta.com/ 论坛类的网站好像生效后又重置了

**Comment by bamf2077** [comment]
> @francis-zhao http://bbs.pcbeta.com/ 论坛类的网站好像生效后又重置了

emmmmm 我试了试，Tampermonkey 通过 `<style>` 标签将样式表插入网页 `<head>` 中后生效了，然后 PCBETA 的脚本将所有 `<style>` 标签给移…除…了……
TM 脚本的执行时间设置为 `@run-at document-start` 和 `@run-at document-body` 都不行，只有 `@run-at document-end` 才可以，但是副作用很明显，所有网页都必须等加载完后才会闪动一下刷新字体，很影响浏览体验。

只要你用 Tampermonkey 就无解决办法，只能甩锅给 PCBETA，别的网站都不会有这种操作，建议你改用 Stylus，以 `.user.css` 的形式安装，亲测正常使用。

**Comment by Z-fly** [comment]
> > @francis-zhao http://bbs.pcbeta.com/ 论坛类的网站好像生效后又重置了
> 
> emmmmm 我试了试，Tampermonkey 通过 `<style>` 标签将样式表插入网页 `<head>` 中后生效了，然后 PCBETA 的脚本将所有 `<style>` 标签给移…除…了……
> TM 脚本的执行时间设置为 `@run-at document-start` 和 `@run-at document-body` 都不行，只有 `@run-at document-end` 才可以，但是副作用很明显，所有网页的都必须等加载完后才会变更字体，很影响浏览体验。
> 
> 只要你用 Tampermonkey 就无解决办法，只能甩锅给 PCBETA，别的网站都不会有这种操作，建议你改用 Stylus，以 `.user.css` 的形式安装，亲测正常使用。

呃，我不太懂前端，我想了下，如果要用Tampermonkey ，这个网站是不是就无解了？

**Comment by bamf2077** [comment]
> 
> 
> > > @francis-zhao http://bbs.pcbeta.com/ 论坛类的网站好像生效后又重置了
> > 
> > 
> > emmmmm 我试了试，Tampermonkey 通过 `<style>` 标签将样式表插入网页 `<head>` 中后生效了，然后 PCBETA 的脚本将所有 `<style>` 标签给移…除…了……
> > TM 脚本的执行时间设置为 `@run-at document-start` 和 `@run-at document-body` 都不行，只有 `@run-at document-end` 才可以，但是副作用很明显，所有网页的都必须等加载完后才会变更字体，很影响浏览体验。
> > 只要你用 Tampermonkey 就无解决办法，只能甩锅给 PCBETA，别的网站都不会有这种操作，建议你改用 Stylus，以 `.user.css` 的形式安装，亲测正常使用。
> 
> 呃，我不太懂前端，所以这个网站还有没有解？如果有解的话直接更新到你的脚本里

建议改用 Stylus 扩展 + `.user.css`，网页直接显示的就是“思源黑体”，如果你只想继续使用 Tampermonkey，可以考虑新建一个脚本，复制下面这段添加进去，不足就是网页先显示“微软雅黑”，然后全部加载完成后，页面字体刷新成“思源黑体”。

```javascript
// ==UserScript==
// @name         PCBETA 字体替换
// @namespace    franciszhao
// @version      0.1
// @description  PCBETA 字体替换
// @match        *://*.pcbeta.com/*
// @grant        GM_addStyle
// @run-at       document-end
// ==/UserScript==

(function () {
  'use strict';

  const css = '* { font-family: "Source Han Sans SC", "Noto Sans CJK SC", "HanHei SC", "方正兰亭黑_GB18030", "方正兰亭黑_GBK", system-ui, -apple-system, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji", emoji; } button, input, keygen, optgroup, select, textarea { font-family: inherit; } code, kbd, pre, samp { font-family: "Source Han Mono SC", "Noto Sans Mono CJK SC", "Source Code Pro", "Noto Mono", "Roboto Mono", "Source Han Sans SC", "Noto Sans CJK SC", "HanHei SC", "方正兰亭黑_GB18030", "方正兰亭黑_GBK", system-ui, -apple-system, monospace, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji", emoji; }';

  if (typeof GM_addStyle !== 'undefined') {
    GM_addStyle(css);
  } else {
    const styleNode = document.createElement('style');
    styleNode.appendChild(document.createTextNode(css));
    (document.querySelector('head') || document.documentElement).appendChild(styleNode);
  }
}());
```

**Comment by Z-fly** [comment]
谢谢！！！

**Comment by Z-fly** [comment]
@francis-zhao 再问下Stylus脚本是怎么写的？
![image](https://user-images.githubusercontent.com/10470892/104830686-03749500-58bc-11eb-993f-8c910b98e0c2.png)

**Comment by bamf2077** [comment]
> 
> 
> @francis-zhao 再问下Stylus脚本是怎么写的？
> ![image](https://user-images.githubusercontent.com/10470892/104830686-03749500-58bc-11eb-993f-8c910b98e0c2.png)

参考这个链接：https://github.com/openstyles/stylus/wiki/Writing-UserCSS

你新建样式表时没有打勾“作为 UserCSS 样式”，把这个选上再新建。
