### ISSUE TITLE
更新到2.5.1版本后字体替换效果不如之前版本

### ISSUE THREAD

**Issue by nicelake** [francis-zhao/userstyles#16]
更新到2.5.1版本后字体替换效果不如之前版本。
如恩山论坛、Chiphell等Discuz论坛的帖子列表，字体仍然被继承到雅黑。
![屏幕截图 2023-11-15 205859](https://github.com/francis-zhao/userstyles/assets/13060372/b523030e-b1ad-4d7c-964a-a55bed551456)

**Comment by noodles500kg** [comment]
我也发现了，还是上个版本好点，有些页面之前版本都能指定字体，新版本反而不行了

**Comment by bamf2077** [comment]
样式表的话试试 v2.5.2，上次因为图标字体被强制替换无法显示把字体替换规则临时禁用了。脚本的话暂时没精力更新，建议改用样式表。

**Comment by nicelake** [comment]
感谢作者更新，问题解决
