### ISSUE TITLE
可否考虑出一个全局苹方🙏

### ISSUE THREAD

**Issue by ice42cream** [francis-zhao/userstyles#9]
全局思源黑体在Mac上看起来有点太细了，而且和系统有点割裂。

**Comment by bamf2077** [comment]
但是 macOS 默认字体不就是苹方吗哈哈哈哈哈，为什么还要全局苹方？

**Comment by ice42cream** [comment]
发issue的时候Safari在某些网站的字体表现不太正常，比如百度百科正文的字体是一种很丑的宋体
<img width="930" alt="截屏2022-02-03 10 41 10" src="https://user-images.githubusercontent.com/36615067/152272742-5c920dfc-19aa-4534-aab6-98ff8416d601.png">
现在已经修复了，但是目录还是原来的样式。暂时还没发现别的网站有问题，这个issue可能不一定需要了吧。

**Comment by bamf2077** [comment]
今天早上更新了 v2.3.0 版本，我用 Windows上的 Firefox 看起来是正常的，你那边方便了测试一下看看，如果百度百科目录样式还是宋体我晚点再提交个 v2.3.1 强制替换一下。

至于全局苹方可以安排上，这两天有空了就更新哈哈哈哈哈哈希望不要鸽子精附体。

**Comment by ice42cream** [comment]
全局思源黑体一直是可以正常工作的😂，上面的截图是未启用脚本的样子。感谢作者🙏。

**Comment by bamf2077** [comment]
忘了这回事了拖了好久哈哈哈哈哈，“全局苹方”测试版本，欢迎试用：
https://greasyfork.org/zh-CN/scripts/453435
